/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package globalway;

import DATOS.Conexion;
import static globalway.JSON.obj;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Nacho
 */
public class Frame2 extends javax.swing.JFrame {
    Conexion conecion = new Conexion();
    Connection cin  = conecion.Conectar();

    
    
    public Frame2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLACTUALIZAR = new javax.swing.JLabel();
        LBLCOMIACTUALIZAR = new javax.swing.JLabel();
        LBLSEDEACTUALIZAR1 = new javax.swing.JLabel();
        LBLID_Moneda = new javax.swing.JLabel();
        TXTCambio = new javax.swing.JTextField();
        TXTNombre_Moneda = new javax.swing.JTextField();
        TXTID_Moneda = new javax.swing.JTextField();
        LBLPOR = new javax.swing.JLabel();
        BTBELIMINAR = new javax.swing.JButton();
        BTBVERSEDES1 = new javax.swing.JButton();
        BTBAGREGAR = new javax.swing.JButton();
        BTBMODIFICAR = new javax.swing.JButton();
        BTNVOLVER = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        LBLUBICACTUALIZAR1 = new javax.swing.JLabel();
        TXTID1 = new javax.swing.JTextField();
        LBLSEDEACTUALIZAR2 = new javax.swing.JLabel();
        TXTNOMBREACT2 = new javax.swing.JTextField();
        LBLCOMIACTUALIZAR1 = new javax.swing.JLabel();
        TXTCOMIACT1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablamoneda = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        LBLIMAGE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLACTUALIZAR.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        LBLACTUALIZAR.setForeground(new java.awt.Color(255, 255, 255));
        LBLACTUALIZAR.setText("ACTUALIZACION DE SEDES");
        getContentPane().add(LBLACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        LBLCOMIACTUALIZAR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLCOMIACTUALIZAR.setForeground(new java.awt.Color(255, 255, 255));
        LBLCOMIACTUALIZAR.setText("Tipo Cambio");
        getContentPane().add(LBLCOMIACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        LBLSEDEACTUALIZAR1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLSEDEACTUALIZAR1.setForeground(new java.awt.Color(255, 255, 255));
        LBLSEDEACTUALIZAR1.setText("Nombre moneda :");
        getContentPane().add(LBLSEDEACTUALIZAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, 30));

        LBLID_Moneda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLID_Moneda.setForeground(new java.awt.Color(255, 255, 255));
        LBLID_Moneda.setText("ID Moneda :");
        getContentPane().add(LBLID_Moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        TXTCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCambioActionPerformed(evt);
            }
        });
        TXTCambio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCambioKeyTyped(evt);
            }
        });
        getContentPane().add(TXTCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 180, 30));

        TXTNombre_Moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNombre_MonedaActionPerformed(evt);
            }
        });
        TXTNombre_Moneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNombre_MonedaKeyTyped(evt);
            }
        });
        getContentPane().add(TXTNombre_Moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 180, 30));

        TXTID_Moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTID_MonedaActionPerformed(evt);
            }
        });
        TXTID_Moneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTID_MonedaKeyTyped(evt);
            }
        });
        getContentPane().add(TXTID_Moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 180, 30));

        LBLPOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconfinder_percent_2460294.png"))); // NOI18N
        getContentPane().add(LBLPOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 208, 50, 30));

        BTBELIMINAR.setText("Eliminar");
        BTBELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBELIMINARActionPerformed(evt);
            }
        });
        getContentPane().add(BTBELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 170, 30));

        BTBVERSEDES1.setText("Ver Sedes");
        BTBVERSEDES1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBVERSEDES1ActionPerformed(evt);
            }
        });
        getContentPane().add(BTBVERSEDES1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 160, 30));

        BTBAGREGAR.setText("Agregar");
        BTBAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBAGREGARActionPerformed(evt);
            }
        });
        getContentPane().add(BTBAGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 150, 30));

        BTBMODIFICAR.setText("Modificar");
        BTBMODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBMODIFICARActionPerformed(evt);
            }
        });
        getContentPane().add(BTBMODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 160, 30));

        BTNVOLVER.setText("Ingresar");
        BTNVOLVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVOLVERActionPerformed(evt);
            }
        });
        getContentPane().add(BTNVOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 130, 30));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Sede", "Nombre Sede", "Comision"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 410, 240));

        LBLUBICACTUALIZAR1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLUBICACTUALIZAR1.setForeground(new java.awt.Color(255, 255, 255));
        LBLUBICACTUALIZAR1.setText("ID Sede :");
        getContentPane().add(LBLUBICACTUALIZAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        TXTID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTID1ActionPerformed(evt);
            }
        });
        TXTID1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTID1KeyTyped(evt);
            }
        });
        getContentPane().add(TXTID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, 30));

        LBLSEDEACTUALIZAR2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLSEDEACTUALIZAR2.setForeground(new java.awt.Color(255, 255, 255));
        LBLSEDEACTUALIZAR2.setText("Nombre de sede :");
        getContentPane().add(LBLSEDEACTUALIZAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        TXTNOMBREACT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNOMBREACT2ActionPerformed(evt);
            }
        });
        TXTNOMBREACT2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNOMBREACT2KeyTyped(evt);
            }
        });
        getContentPane().add(TXTNOMBREACT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 180, 30));

        LBLCOMIACTUALIZAR1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLCOMIACTUALIZAR1.setForeground(new java.awt.Color(255, 255, 255));
        LBLCOMIACTUALIZAR1.setText("Comision :");
        getContentPane().add(LBLCOMIACTUALIZAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        TXTCOMIACT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCOMIACT1ActionPerformed(evt);
            }
        });
        TXTCOMIACT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCOMIACT1KeyTyped(evt);
            }
        });
        getContentPane().add(TXTCOMIACT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 180, 30));

        tablamoneda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Moneda", "Nombre Moneda", "Tipo Cambio"
            }
        ));
        jScrollPane3.setViewportView(tablamoneda);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 410, 240));

        jButton1.setText("Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, -1, -1));

        LBLIMAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue-gradient-green-linear-1920x1080-c2-0000cd-41f012-a-300-f-14.jpg"))); // NOI18N
        LBLIMAGE.setText("jLabel1");
        getContentPane().add(LBLIMAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 921, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCambioActionPerformed

    private void TXTNombre_MonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNombre_MonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombre_MonedaActionPerformed

    private void TXTID_MonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTID_MonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTID_MonedaActionPerformed

    private void BTNVOLVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVOLVERActionPerformed
     JFGlobal global =new JFGlobal ();
     global.setVisible(true);
     dispose();
    }//GEN-LAST:event_BTNVOLVERActionPerformed

    private void BTBAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBAGREGARActionPerformed
         if(TXTID1.getText().equals("") || TXTNOMBREACT2.getText().equals("")|| TXTCOMIACT1.getText().equals("")||TXTID_Moneda.getText().equals("") || TXTNombre_Moneda.getText().equals("")|| TXTCambio.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Hay campos vacios ");
         }else{ 
         
        try{
             
CallableStatement insert=cin.prepareCall("{call INSERT_SEDE(?,?,?)}");
insert.setString(1,TXTID1.getText());
insert.setString(2,TXTNOMBREACT2.getText());
insert.setString(3,TXTCOMIACT1.getText());
insert.execute();
//JOptionPane.showMessageDialog(null,"Registro exitoso");

}
catch(Exception e){
JOptionPane.showMessageDialog(null,"Registro fallido" + e);
}
     try{
         CallableStatement insert1=cin.prepareCall("{call INSERT_MONEDA(?,?,?)}");
insert1.setString(1,TXTID_Moneda.getText());
insert1.setString(2,TXTNombre_Moneda.getText());
insert1.setString(3,TXTCambio.getText());
insert1.execute();
         TXTID1.setText(null);
         TXTNOMBREACT2.setText(null);
         TXTCOMIACT1.setText(null);
         TXTID_Moneda.setText(null);
         TXTNombre_Moneda.setText(null);
         TXTCambio.setText(null);
JOptionPane.showMessageDialog(null,"Registro exitoso");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,"Registro fallido" + e);
}
     }   
    }//GEN-LAST:event_BTBAGREGARActionPerformed

    private void BTBELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBELIMINARActionPerformed
  try{
CallableStatement Delete=cin.prepareCall("{call DELETE_SEDE(?)}");
Delete.setString(1,TXTID1.getText());
Delete.execute();
//JOptionPane.showMessageDialog(null,"Registro Eliminado");

}
catch(Exception e){
JOptionPane.showMessageDialog(null,"Eliminacion fallida" + e);
}
  
  try{
CallableStatement Delete1=cin.prepareCall("{call DELETE_MONEDA(?)}");
Delete1.setString(1,TXTID_Moneda.getText());
Delete1.execute();
JOptionPane.showMessageDialog(null,"Registro Eliminado");

}
catch(Exception e){
JOptionPane.showMessageDialog(null,"Eliminacion fallida" + e);
}
  
    }//GEN-LAST:event_BTBELIMINARActionPerformed

    private void BTBMODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBMODIFICARActionPerformed
        try{
CallableStatement Update=cin.prepareCall("{call UPDATE_SEDE(?,?,?)}");
Update.setString(1,TXTID1.getText());
Update.setString(2,TXTNOMBREACT2.getText());
Update.setString(3,TXTCOMIACT1.getText());

Update.execute();
JOptionPane.showMessageDialog(null,"Registro  modificado");

}
catch(Exception e){
JOptionPane.showMessageDialog(null,"Modificacion fallida" + e);
}
        
        try{
CallableStatement Update1=cin.prepareCall("{call UPDATE_MONEDA(?,?,?)}");
Update1.setString(1,TXTID_Moneda.getText());
Update1.setString(2,TXTNombre_Moneda.getText());
Update1.setString(3,TXTCambio.getText());

Update1.execute();
JOptionPane.showMessageDialog(null,"Registro modificado");

}
catch(Exception e){
JOptionPane.showMessageDialog(null,"Modificacion fallida" + e);
}

    }//GEN-LAST:event_BTBMODIFICARActionPerformed

    private void BTBVERSEDES1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBVERSEDES1ActionPerformed
    cargarTable();
    cargarTable2();
    
    }//GEN-LAST:event_BTBVERSEDES1ActionPerformed

    private void TXTID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTID1ActionPerformed

    private void TXTNOMBREACT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNOMBREACT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNOMBREACT2ActionPerformed

    private void TXTCOMIACT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCOMIACT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCOMIACT1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FileWriter file = null;
        try {
            file = new FileWriter("practica.json");
            file.write("Archivo: \n [\n");
            for(int h=0;h<=5;h++){
                obj.put("conteo",h);
                file.write(" "+obj.toString()+"\n");
            }   file.write("\n");
            file.write("]");
            file.flush();
        } catch (IOException ex) {
            Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                file.close();
            } catch (IOException ex) {
                Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TXTID1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTID1KeyTyped
       char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Valor ingresado no valido, ingrese solo números");
        }
        
    }//GEN-LAST:event_TXTID1KeyTyped

    private void TXTCOMIACT1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCOMIACT1KeyTyped
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Valor ingresado no valido, ingrese solo números");
        }
        
    }//GEN-LAST:event_TXTCOMIACT1KeyTyped

    private void TXTCambioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCambioKeyTyped
      char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Valor ingresado no valido, ingrese solo números");
        }
        
    }//GEN-LAST:event_TXTCambioKeyTyped

    private void TXTNOMBREACT2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNOMBREACT2KeyTyped
         char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Valor ingresado no valido");
        }
    }//GEN-LAST:event_TXTNOMBREACT2KeyTyped

    private void TXTID_MonedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTID_MonedaKeyTyped
         char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Valor ingresado no valido");
        }
    }//GEN-LAST:event_TXTID_MonedaKeyTyped

    private void TXTNombre_MonedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNombre_MonedaKeyTyped
         char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Valor ingresado no valido");
        }
    }//GEN-LAST:event_TXTNombre_MonedaKeyTyped
 
     private void cargarTable(){
    
         DefaultTableModel modeloTabla = (DefaultTableModel) tabla.getModel();
         
         modeloTabla.setRowCount(0);
         
         PreparedStatement ps;
         
         ResultSet rs = null;
         ResultSetMetaData rsmd;
         int columnas; 
         
         try{ 
            
             Connection cin  = conecion.Conectar();
             ps = cin.prepareStatement("SELECT ID_Sedes, Nombre_Sede, Comision FROM Sedes" );
            
             rs = ps.executeQuery();
             rsmd = rs.getMetaData();
             columnas = rsmd.getColumnCount();
             
             while(rs.next()){
             
                 Object [] fila = new Object[columnas];
                 for(int indice = 0; indice<columnas; indice++){
                     
                     fila[indice] = rs.getObject(indice + 1);
                 }
                 
                 modeloTabla.addRow(fila);
          
             }
     
         }catch(SQLException e){
             JOptionPane.showMessageDialog(null, e.toString());
         }
       
    
}   

     private void cargarTable2(){
    
         DefaultTableModel modeloTabla = (DefaultTableModel) tablamoneda.getModel();
         
         modeloTabla.setRowCount(0);
         
         PreparedStatement ps;
         
         ResultSet rs = null;
         ResultSetMetaData rsmd;
         int columnas; 
         
         try{ 
            
             Connection cin  = conecion.Conectar();
             ps = cin.prepareStatement("SELECT ID_Moneda, Nombre_Moneda, Tipo_Cambio FROM Monedas" );
            
             rs = ps.executeQuery();
             rsmd = rs.getMetaData();
             columnas = rsmd.getColumnCount();
             
             while(rs.next()){
             
                 Object [] fila = new Object[columnas];
                 for(int indice = 0; indice<columnas; indice++){
                     
                     fila[indice] = rs.getObject(indice + 1);
                 }
                 
                 modeloTabla.addRow(fila);
          
             }
     
         }catch(SQLException e){
             JOptionPane.showMessageDialog(null, e.toString());
         }
       
    
}  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBAGREGAR;
    private javax.swing.JButton BTBELIMINAR;
    private javax.swing.JButton BTBMODIFICAR;
    private javax.swing.JButton BTBVERSEDES1;
    private javax.swing.JButton BTNVOLVER;
    private javax.swing.JLabel LBLACTUALIZAR;
    private javax.swing.JLabel LBLCOMIACTUALIZAR;
    private javax.swing.JLabel LBLCOMIACTUALIZAR1;
    private javax.swing.JLabel LBLID_Moneda;
    private javax.swing.JLabel LBLIMAGE;
    private javax.swing.JLabel LBLPOR;
    private javax.swing.JLabel LBLSEDEACTUALIZAR1;
    private javax.swing.JLabel LBLSEDEACTUALIZAR2;
    private javax.swing.JLabel LBLUBICACTUALIZAR1;
    private javax.swing.JTextField TXTCOMIACT1;
    private javax.swing.JTextField TXTCambio;
    private javax.swing.JTextField TXTID1;
    private javax.swing.JTextField TXTID_Moneda;
    private javax.swing.JTextField TXTNOMBREACT2;
    private javax.swing.JTextField TXTNombre_Moneda;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablamoneda;
    // End of variables declaration//GEN-END:variables
}


