
package globalway;

import DATOS.Conexion;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Nacho
 */
public class JFGlobal extends javax.swing.JFrame {
    Conexion conecion = new Conexion();
    Connection cin  = conecion.Conectar();
    /**
     * Creates new form JFGlobal
     */
    public JFGlobal() {
        
        initComponents();
        llenarCombobox();
        llenarCombobox1();
    }
private void llenarCombobox(){
    
       PreparedStatement ps;
        ResultSet rs = null;   
        
  
     try{ 
           ps = cin.prepareStatement("SELECT * FROM Monedas");
             
            rs = ps.executeQuery();
            
            while(rs.next()){
              
                String  ID = rs.getString("Nombre_Moneda");
                ComboBoxMoneda1.addItem(ID);
                
            }
            

          
         }catch(SQLException e){
             JOptionPane.showMessageDialog(null, e.toString());
         }
    
    }
    
private void llenarCombobox1(){
    
       PreparedStatement ps;
        ResultSet rs = null;   
        
  
     try{ 
           ps = cin.prepareStatement("SELECT * FROM Sedes");
             
            rs = ps.executeQuery();
            
            while(rs.next()){
              
                String  ID = rs.getString("Nombre_Sede");
                ComboBoxRetiras.addItem(ID);
                
            }
            

          
         }catch(SQLException e){
             JOptionPane.showMessageDialog(null, e.toString());
         }
    
    }



//FUNCION DE TRANSFERENCIA DOLAR
    private double TransferenciaDolar(double Cantidad, double TipoCam, double Comision){
        double Dolares;
        double PagoComision;
        double PagoDolares;
        double PagoNacional;

        //USA
        PagoComision = Cantidad * Comision /100; 
        Dolares = (Cantidad / TipoCam)+PagoComision;
        PagoDolares=Dolares;
        PagoNacional = Dolares*TipoCam;      
        
        
      return PagoDolares;   
    }
    //FUNCION DE TRANSFERENCIA Nacional
    private double TransferenciaNacional(double Cantidad, double TipoCam, double Comision){
        double Dolares;
        double PagoComision;
        double PagoDolares;
        double PagoNacional;

        //USA
        PagoComision = Cantidad * Comision /100; 
        Dolares = (Cantidad / TipoCam)+PagoComision;
        PagoDolares=Dolares;
        PagoNacional = Dolares*TipoCam;      
        
        
      return PagoNacional;   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCorreo = new javax.swing.JLabel();
        ComboBoxMonto = new javax.swing.JComboBox<>();
        ComboBoxRetiras = new javax.swing.JComboBox<>();
        LBLGlobalWay = new javax.swing.JLabel();
        LBLComision = new javax.swing.JLabel();
        TxtMonto = new javax.swing.JTextField();
        LBLMonto = new javax.swing.JLabel();
        LBLTipoCambio = new javax.swing.JLabel();
        TxtCantidad = new javax.swing.JTextField();
        TxtTipoCambio = new javax.swing.JTextField();
        LBLUbicacion2 = new javax.swing.JLabel();
        LBLID = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        LBLCorreo1 = new javax.swing.JLabel();
        LBLMonedaComprar1 = new javax.swing.JLabel();
        TxtCorreo1 = new javax.swing.JTextField();
        LBLCantidad1 = new javax.swing.JLabel();
        LBLRetiras = new javax.swing.JLabel();
        LBLPagas = new javax.swing.JLabel();
        TxtComision1 = new javax.swing.JTextField();
        BTNTRANS = new javax.swing.JButton();
        BTNSEDE = new javax.swing.JButton();
        LBLPROCENTAJE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtUbicacion3 = new javax.swing.JTextField();
        LBLNombre1 = new javax.swing.JLabel();
        TxtIdSede = new javax.swing.JTextField();
        ComboBoxMoneda1 = new javax.swing.JComboBox<>();
        BTNBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        LBLIMAGE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 90, 20));

        ComboBoxMonto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolares", "Nacional" }));
        ComboBoxMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMontoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 250, 30));

        ComboBoxRetiras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxRetirasItemStateChanged(evt);
            }
        });
        ComboBoxRetiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxRetirasActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxRetiras, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 250, 30));

        LBLGlobalWay.setFont(new java.awt.Font("Verdana", 3, 48)); // NOI18N
        LBLGlobalWay.setForeground(new java.awt.Color(255, 255, 255));
        LBLGlobalWay.setText("GLOBAL WAY");
        getContentPane().add(LBLGlobalWay, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 400, -1));

        LBLComision.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLComision.setForeground(new java.awt.Color(255, 255, 255));
        LBLComision.setText("Comision");
        getContentPane().add(LBLComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        TxtMonto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TxtMonto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtMonto.setEnabled(false);
        getContentPane().add(TxtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 220, 30));

        LBLMonto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLMonto.setForeground(new java.awt.Color(255, 255, 255));
        LBLMonto.setText("Monto a pagar :");
        getContentPane().add(LBLMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        LBLTipoCambio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLTipoCambio.setForeground(new java.awt.Color(255, 255, 255));
        LBLTipoCambio.setText("Tipo Cambio");
        getContentPane().add(LBLTipoCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        TxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCantidadActionPerformed(evt);
            }
        });
        TxtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCantidadKeyTyped(evt);
            }
        });
        getContentPane().add(TxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 250, 30));

        TxtTipoCambio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TxtTipoCambio.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        TxtTipoCambio.setEnabled(false);
        getContentPane().add(TxtTipoCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 130, 30));

        LBLUbicacion2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLUbicacion2.setForeground(new java.awt.Color(255, 255, 255));
        LBLUbicacion2.setText("Ubicacion");
        getContentPane().add(LBLUbicacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        LBLID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLID.setForeground(new java.awt.Color(255, 255, 255));
        LBLID.setText(" ID Sede");
        getContentPane().add(LBLID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        TxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 250, 30));

        LBLCorreo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        LBLCorreo1.setText("Correo:");
        getContentPane().add(LBLCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        LBLMonedaComprar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLMonedaComprar1.setForeground(new java.awt.Color(255, 255, 255));
        LBLMonedaComprar1.setText("Moneda Comprar:");
        getContentPane().add(LBLMonedaComprar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        TxtCorreo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCorreo1ActionPerformed(evt);
            }
        });
        TxtCorreo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCorreo1KeyTyped(evt);
            }
        });
        getContentPane().add(TxtCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 250, 30));

        LBLCantidad1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLCantidad1.setForeground(new java.awt.Color(255, 255, 255));
        LBLCantidad1.setText("Cantidad:");
        getContentPane().add(LBLCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        LBLRetiras.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLRetiras.setForeground(new java.awt.Color(255, 255, 255));
        LBLRetiras.setText("Retiras en :");
        getContentPane().add(LBLRetiras, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        LBLPagas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLPagas.setForeground(new java.awt.Color(255, 255, 255));
        LBLPagas.setText("Pagas con :");
        getContentPane().add(LBLPagas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 130, -1));

        TxtComision1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TxtComision1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtComision1.setEnabled(false);
        getContentPane().add(TxtComision1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 150, 30));

        BTNTRANS.setText("Transferencia");
        BTNTRANS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTRANSActionPerformed(evt);
            }
        });
        getContentPane().add(BTNTRANS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 130, 30));

        BTNSEDE.setText("Calculo");
        BTNSEDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSEDEActionPerformed(evt);
            }
        });
        getContentPane().add(BTNSEDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 130, 30));

        LBLPROCENTAJE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconfinder_percent_2460294.png"))); // NOI18N
        getContentPane().add(LBLPROCENTAJE, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconfinder_Finance_currency_exchange_1889190.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 80, -1));

        TxtUbicacion3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TxtUbicacion3.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        TxtUbicacion3.setEnabled(false);
        getContentPane().add(TxtUbicacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 140, 30));

        LBLNombre1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLNombre1.setForeground(new java.awt.Color(255, 255, 255));
        LBLNombre1.setText("Nombre:");
        getContentPane().add(LBLNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        TxtIdSede.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtIdSedeKeyTyped(evt);
            }
        });
        getContentPane().add(TxtIdSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 50, 30));

        ComboBoxMoneda1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxMoneda1ItemStateChanged(evt);
            }
        });
        ComboBoxMoneda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMoneda1ActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxMoneda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 250, 30));

        BTNBuscar.setText("Buscar");
        BTNBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 30));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 150, 30));

        LBLIMAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue-gradient-green-linear-1920x1080-c2-0000cd-41f012-a-300-f-14.jpg"))); // NOI18N
        LBLIMAGE.setText("jLabel1");
        getContentPane().add(LBLIMAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 1180, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSEDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSEDEActionPerformed
        double Cantidad = Double.parseDouble(TxtCantidad.getText());
        double TipoCam = Double.parseDouble(TxtTipoCambio.getText());
        double Comision = Double.parseDouble(TxtComision1.getText());

        String operacion1 = ComboBoxMonto.getSelectedItem().toString();
        int operacion2 = ComboBoxMonto.getSelectedIndex();
        if (operacion2 == 0) {
            String Resultado = Double.toString(TransferenciaDolar(Cantidad, TipoCam, Comision));
            TxtMonto.setText(Resultado);
        } else {
            if (operacion2 == 1) {
                String Resultado = Double.toString(TransferenciaNacional(Cantidad, TipoCam, Comision));
            TxtMonto.setText(Resultado);
            }
        }  
    }//GEN-LAST:event_BTNSEDEActionPerformed

    private void BTNTRANSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTRANSActionPerformed
 
        if(TxtIdSede.getText().equals("") || TxtNombre.getText().equals("")||  TxtCorreo1.getText().equals("")||  TxtCantidad.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Hay campos vacios ");
         }else{
        
                try {
                    CallableStatement insert = cin.prepareCall("{call INSERT_TRANS(?,?,?,?,?,?,?,?)}");

                    insert.setString(1, TxtIdSede.getText());
                    insert.setString(2, TxtNombre.getText());
                    insert.setString(3, TxtCorreo1.getText());
                    insert.setString(4, ComboBoxMoneda1.getSelectedItem().toString());
                    insert.setString(5, TxtCantidad.getText());
                    insert.setString(6, ComboBoxRetiras.getSelectedItem().toString());
                    insert.setString(7, ComboBoxMonto.getSelectedItem().toString());
                    insert.setString(8, TxtMonto.getText());
                    insert.execute();

                    JOptionPane.showMessageDialog(null, "Registro exitoso");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Registro fallido" + e);
                }
 }
         
         try {
            
            String nombre=TxtNombre.getText();
            String correo=TxtCorreo1.getText();
            String moneda=ComboBoxMoneda1.getSelectedItem().toString();
            String retiras=ComboBoxRetiras.getSelectedItem().toString();
            String pagas=ComboBoxMonto.getSelectedItem().toString();
            String monto=TxtMonto.getText();
            String cantidad=TxtCantidad.getText();
            
            String envio= nombre + ","+correo + "," + moneda + ","+ retiras + "," +pagas+ "," + monto + "," + cantidad + ",";
            
                                
                    TxtIdSede.setText(null);
                    TxtNombre.setText(null);
                    TxtCorreo1.setText(null);
                    TxtCantidad.setText(null);
                    TxtUbicacion3.setText(null);
                    TxtTipoCambio.setText(null);
                    TxtComision1.setText(null);
                    TxtMonto.setText(null);
                   
            Socket cliente = null;
            DataInputStream entrada = null;
            DataOutputStream salida = null;
            String ipServidor ="127.0.0.1";
            
            cliente = new Socket(ipServidor, 2020);
           
            entrada = new DataInputStream(cliente.getInputStream());
          
            salida = new DataOutputStream(cliente.getOutputStream());
            
            
            salida.writeBytes(envio);                                   
            salida.close();
            entrada.close();
            cliente.close();
  
        } catch (IOException ex) {
            Logger.getLogger(JFGlobal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNTRANSActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void ComboBoxRetirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxRetirasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxRetirasActionPerformed

    private void ComboBoxMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMontoActionPerformed

    private void ComboBoxMoneda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMoneda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMoneda1ActionPerformed

    private void BTNBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarActionPerformed
        PreparedStatement ps;
        ResultSet rs = null;   
        
    
     
     
     try{ 
           ps = cin.prepareStatement("SELECT ID_Sedes, Nombre_Sede, Comision FROM Sedes WHERE ID_Sedes=?");
           int ID = Integer.parseInt(TxtIdSede.getText());
            ps.setInt(1, ID);
            rs = ps.executeQuery();
            
            if(rs.next() == false){
                JOptionPane.showMessageDialog(this, "No encontrado");
               
                TxtUbicacion3.setText("");
                TxtComision1.setText("");
                TxtIdSede.requestFocus();
                        
            }
            else{
                
                TxtUbicacion3.setText(rs.getString("Nombre_Sede"));
                TxtComision1.setText(rs.getString("Comision"));
                
            }
            
           
         }catch(SQLException e){
             JOptionPane.showMessageDialog(null, e.toString());
         }
    }//GEN-LAST:event_BTNBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Frame2 principal =new Frame2 ();
     principal.setVisible(true);
     dispose();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboBoxMoneda1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxMoneda1ItemStateChanged
       PreparedStatement ps1;
        ResultSet rs1 = null;   
        
    
     
     
     try{ 
           ps1 = cin.prepareStatement("EXEC MOSTRAR_MONEDA ?,?");
           String ID = (String)ComboBoxMoneda1.getSelectedItem();
            ps1.setString(1, ID);
            ps1.setString(2, "Select Moneda");
            rs1 = ps1.executeQuery();
            
            if(rs1.next() == false){
                JOptionPane.showMessageDialog(this, "No encontrado");
            }
            else{
           TxtTipoCambio.setText(rs1.getString("Tipo_Cambio"));
            }
             
     }catch(SQLException e){
             JOptionPane.showMessageDialog(null, e.toString());
         }
    }//GEN-LAST:event_ComboBoxMoneda1ItemStateChanged

    private void ComboBoxRetirasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxRetirasItemStateChanged
         PreparedStatement ps1;
        ResultSet rs1 = null;   
        
    
     
     
     try{ 
           ps1 = cin.prepareStatement("EXEC MOSTRAR_MONEDA ?,?");
           String ID = (String)ComboBoxRetiras.getSelectedItem();
            ps1.setString(1, ID);
            ps1.setString(2, "Select Retiras");
            rs1 = ps1.executeQuery();
            
            if(rs1.next() == false){
                JOptionPane.showMessageDialog(this, "No encontrado");
            }
            else{
           TxtComision1.setText(rs1.getString("Comision"));
            }
             
     }catch(SQLException e){
             JOptionPane.showMessageDialog(null, e.toString());
         }
    }//GEN-LAST:event_ComboBoxRetirasItemStateChanged

    private void TxtIdSedeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdSedeKeyTyped
 char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Valor ingresado no valido, ingrese solo números");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdSedeKeyTyped

    private void TxtCorreo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCorreo1ActionPerformed

    }//GEN-LAST:event_TxtCorreo1ActionPerformed

    private void TxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCantidadActionPerformed

    private void TxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyTyped
    char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Valor ingresado no valido");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreKeyTyped

    private void TxtCorreo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorreo1KeyTyped

    }//GEN-LAST:event_TxtCorreo1KeyTyped

    private void TxtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCantidadKeyTyped
 char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Valor ingresado no valido, ingrese solo números");
        }
        


        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGlobal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscar;
    private javax.swing.JButton BTNSEDE;
    private javax.swing.JButton BTNTRANS;
    private javax.swing.JComboBox<String> ComboBoxMoneda1;
    private javax.swing.JComboBox<String> ComboBoxMonto;
    private javax.swing.JComboBox<String> ComboBoxRetiras;
    private javax.swing.JLabel LBLCantidad1;
    private javax.swing.JLabel LBLComision;
    private javax.swing.JLabel LBLCorreo1;
    private javax.swing.JLabel LBLGlobalWay;
    private javax.swing.JLabel LBLID;
    private javax.swing.JLabel LBLIMAGE;
    private javax.swing.JLabel LBLMonedaComprar1;
    private javax.swing.JLabel LBLMonto;
    private javax.swing.JLabel LBLNombre1;
    private javax.swing.JLabel LBLPROCENTAJE;
    private javax.swing.JLabel LBLPagas;
    private javax.swing.JLabel LBLRetiras;
    private javax.swing.JLabel LBLTipoCambio;
    private javax.swing.JLabel LBLUbicacion2;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtComision1;
    private javax.swing.JTextField TxtCorreo1;
    private javax.swing.JTextField TxtIdSede;
    private javax.swing.JTextField TxtMonto;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTipoCambio;
    private javax.swing.JTextField TxtUbicacion3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCorreo;
    // End of variables declaration//GEN-END:variables
}
